/*
 * CORE-PromptManager-API
 * Prompt Manager REST API Endpoints
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.langframework.promptmanager.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CategoryModel
 */
public class CategoryModelTest {
    private final CategoryModel model = new CategoryModel();

    /**
     * Model tests for CategoryModel
     */
    @Test
    public void testCategoryModel() {
        // TODO: test CategoryModel
    }

    /**
     * Test the property 'categoryName'
     */
    @Test
    public void categoryNameTest() {
        // TODO: test categoryName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
